# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 72ea1dc75ea543f7b274b1c38ee36a9d735ddab40c0250c231d5b0f0110eeb33984ea5f4d16a9e3e2d1b0b7e9e400cddd97f4d2a0f39e05783ae933559ca3005

test:
  secret_key_base: 27d902d2f5d65a505433738f8e0bd9049b4ae721cbf4ddc1d8150e4952db9be243b64ffcf1f0b6ae85451b08c4e433ff382f0f1fce557387865263f6c8de7794

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: Test
  secret_token: Test
